version: '3.7'
services:
    postgres:
        container_name: comet-postgres
        image: 'postgres'
        env_file:
            - database.env
        volumes:
            - ./data/postgres:/var/lib/postgresql/data/
            - ./init:/docker-entrypoint-initdb.d
        expose:
            - '5432'
        ports:
            - 5433:5432

